use ctp;

CREATE TABLE ctp
(
id                 bigint not null auto_increment,
TradingDay         varchar(9),
InstrumentID       varchar(7),
ExchangeID         varchar(9),
LastPrice          float,
PreSettlementPrice float,
PreClosePrice      float,
PreOpenInterest    float,
OpenPrice          float,
HighestPrice       float,
LowestPrice        float,
Volume             int unsigned,
Turnover           float,
OpenInterest       float,
ClosePrice         float,
SettlementPrice    float,
UpdateTime         varchar(9),
UpdateMillisec     int unsigned,
BidPrice1          float,
BidVolume1         int unsigned, 
AskPrice1          float,
AskVolume1         int unsigned,
BidPrice2          float,
BidVolume2         int unsigned, 
AskPrice2          float,
AskVolume2         int unsigned,
BidPrice3          float,
BidVolume3         int unsigned, 
AskPrice3          float,
AskVolume3         int unsigned,
BidPrice4          float,
BidVolume4         int unsigned, 
AskPrice4          float,
AskVolume4         int unsigned,
BidPrice5          float,
BidVolume5         int unsigned, 
AskPrice5          float,
AskVolume5         int unsigned,
AveragePrice       float,
BidMoney1          bigint unsigned,
BidMoney2          bigint unsigned,
BidMoney3          bigint unsigned,
BidMoney4          bigint unsigned,
BidMoney5          bigint unsigned,
AskMoney1          bigint unsigned,
AskMoney2          bigint unsigned,
AskMoney3          bigint unsigned,
AskMoney4          bigint unsigned,
AskMoney5          bigint unsigned,
MaxBidMoney        bigint unsigned,
MaxAskMoney        bigint unsigned,
primary key (id),
INDEX MaxBidMoney_index (MaxBidMoney),  
INDEX MaxAskMoney_index (MaxAskMoney)  
) ENGINE=InnoDB;
